<a href="https://colab.research.google.com/github/bofori-tech/DS-Unit-1-Sprint-2-Statistics/blob/master/Copy_of_LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip

--2020-07-26 02:38:54--  https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 20478 (20K) [application/x-httpd-php]
Saving to: ‘student.zip’

student.zip         100%[===================>]  20.00K  --.-KB/s    in 0.1s    

2020-07-26 02:38:54 (145 KB/s) - ‘student.zip’ saved [20478/20478]



In [ ]:
!unzip 'student.zip'

Archive:  student.zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [ ]:
import pandas as pd
scores= pd.read_csv('student-mat.csv',sep=';')
scores.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

In [ ]:
#Remove null values
scores.isnull().sum()

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [ ]:
#imports
from scipy.stats import ttest_ind, ttest_1samp
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
scores.describe(exclude='number')

school  sex address famsize  ... nursery higher internet romantic
count     395  395     395     395  ...     395    395      395      395
unique      2    2       2       2  ...       2      2        2        2
top        GP    F       U     GT3  ...     yes    yes      yes       no
freq      349  208     307     281  ...     314    375      329      263

[4 rows x 17 columns]

In [ ]:
#Two pairs of variables that are dependant.
scores['famsize'].value_counts()

GT3    281
LE3    114
Name: famsize, dtype: int64

In [ ]:
scores['school'].value_counts()

GP    349
MS     46
Name: school, dtype: int64

In [ ]:
equ=pd.crosstab(scores['Pstatus'], scores['school'])
equ

school    GP  MS
Pstatus         
A         38   3
T        311  43

In [ ]:
#to test
from scipy.stats import chisquare
chisquare(equ, axis = None)

Power_divergenceResult(statistic=617.8911392405063, pvalue=1.332726759628308e-133)

In [ ]:
#pvalue is close to zero, we reject the null hypothesis
#The null hypothesis that there is no relation between famsize and the school one attends
#Two pairs of variables that are dependant.

In [ ]:
#Two sets of variables that are independent 
success=pd.crosstab(scores['sex'], scores['Pstatus'])
success


Pstatus   A    T
sex             
F        23  185
M        18  169

In [ ]:
chisquare(success, axis=None)

Power_divergenceResult(statistic=249.4455696202532, pvalue=8.624649148858084e-54)

In [ ]:
#pvalue is close to zero, we reject the null hypothesis


In [ ]:
import scipy.stats as stats
#Mjob and Reason
xtab=pd.crosstab(scores['Mjob'], scores['reason'])
xtab



reason    course  home  other  reputation
Mjob                                     
at_home       31    12      7           9
health         6     9      6          13
other         46    47      8          40
services      37    25     11          30
teacher       25    16      4          13

In [ ]:
stats.chi2_contingency(xtab)

(22.946281576618656,
 0.02818547173558085,
 12,
 array([[21.65822785, 16.28101266,  5.37721519, 15.6835443 ],
        [12.48101266,  9.38227848,  3.09873418,  9.03797468],
        [51.75949367, 38.90886076, 12.85063291, 37.48101266],
        [37.81012658, 28.42278481,  9.38734177, 27.37974684],
        [21.29113924, 16.00506329,  5.28607595, 15.41772152]]))

In [ ]:
stats.chi2_contingency(xtab)[1]

0.02818547173558085

In [ ]:
#pvalue is less than 0.05, we reject that hypothesis.

In [ ]:
xdab=pd.crosstab(scores['address'], scores['activities'])
xdab

activities   no  yes
address             
R            39   49
U           155  152

In [ ]:
stats.chi2_contingency(xdab)
stats.chi2_contingency(xdab)[1]

0.36821265378813683

In [ ]:
#pvalue is above .05
#We fail to reject the null hypothesis.


### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [ ]:
# Mjob and Reason
observed=pd.crosstab(scores['Mjob'], scores['reason']).values

In [ ]:
# chi square test
chi_squared, p_value, dof, expected = stats.chi2_contingency(observed)

print(f"Chi-Squared: {chi_squared}")
print(f"P-value: {p_value}")
print(f"Degrees of Freedom: {dof}") 
print("Expected: \n", np.array(expected))

Chi-Squared: 22.946281576618656
P-value: 0.02818547173558085
Degrees of Freedom: 12
Expected: 
 [[21.65822785 16.28101266  5.37721519 15.6835443 ]
 [12.48101266  9.38227848  3.09873418  9.03797468]
 [51.75949367 38.90886076 12.85063291 37.48101266]
 [37.81012658 28.42278481  9.38734177 27.37974684]
 [21.29113924 16.00506329  5.28607595 15.41772152]]


In [ ]:
#Pvalue is >.05, we reject the null hypothesis.

## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)